name: CI

on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs: 
  tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Install dotnet
        uses: actions/setup-dotnet@v6
        
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        run: |
          mkdir -p ./TestResults
          find tests/ -type f -name "*Tests.dll" -path "*/bin/Release/*" | while read -r test_dll; do
            echo "Running tests in: $test_dll"
            dotnet exec "$test_dll"
          done